apiVersion: apps/v1
kind: Deployment
metadata:
  name: section11-app
spec:
  selector:
    matchLabels:
      app: section11
  replicas: 3
  template:
    metadata:
      labels:
        app: section11
    spec:
      containers:
        - name: section11-app
          image: johncarnell/tmx-licensing-service:section11
          ports:
            - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: section11-service
spec:
  selector:
    app: section11
  ports:
    - port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: section11-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.mytest.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: section11-service
                port:
                  number: 8080